### ISSUE TITLE
Can't run test script

### ISSUE THREAD

**Issue by aja9675** [NVlabs/DeepIM-PyTorch#6]
I can successfully run the demo and training script, but testing fails with the following error:
Traceback (most recent call last):
  File "./tools/test_net.py", line 145, in <module>
    test(dataloader, background_loader, network, output_dir)
  File "/home/.../DeepIM-PyTorch/tools/../lib/fcn/train_test.py", line 752, in test
    grids = nn.functional.affine_grid(affine_matrices, inputs.size())
  File "/home/.../deepim_env/lib/python3.6/site-packages/torch/nn/functional.py", line 4084, in affine_grid
    raise ValueError("Expected non-zero, positive output size. Got {}".format(size))
ValueError: Expected non-zero, positive output size. Got torch.Size([0, 6, 480, 640])

Works:
./experiments/scripts/demo.sh
./experiments/scripts/ycb_video_flow_train.sh

Does not work:
./experiments/scripts/ycb_video_flow_test.sh

**Comment by aja9675** [comment]
Figured it out.  'results_posecnn' was not where it should have been.

**Comment by BigBuffa1o** [comment]
Can you help me upload the pretrained model and post results that are destroyed by author? that's very important to me , thank you so much!
